language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt --use-mirrors
# command to run tests
script: ./filebutler/manage.py --delete-expired-data

notifications:
    irc: "irc.freenode.org#kurbitz"
